class DummyDb {
  static List imgUrls = [
    'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/i/e/l/l-ausk0556-ausk-original-imagt4syszf9gq5f.jpeg?q=70&crop=true',
    'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/r/z/l/s-gucci-tshirt-sti-original-imahyyzs4kpgbfby.jpeg?q=70&crop=true',
    'https://m.media-amazon.com/images/I/71zRMNf2uvL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/41oLEGgijDL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81gHzitlpsL._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/51dPz+dQTZL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/51ymWaWO2mL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/71Xgx41+NyL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81qu3nXwc+L._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/51dPz+dQTZL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/51yHL2fq9DL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/71gBQOlwuHL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/71cpG1tSisL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/717Ay1OQ6ZL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81f8Wtfa0WL._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/81HZfmop2qS._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/71qsgN7duuL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/819AlR14qyL._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/81YOJm4PSbS._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/61TFwLnRngL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/71L4tro44ML._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81Jb8LZKohL._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/71T-opdfScL._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81qY09mAi7L._AC_SX679_.jpg',
    'https://m.media-amazon.com/images/I/81h9q1Nm+9L._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/81CRt8tjc3L._AC_SX569_.jpg',
    'https://m.media-amazon.com/images/I/81oi32BML7L._AC_SX679_.jpg',
  ];

  static List nameAnddetails = [
    {"name": "Regular fit slogan", "model": "INR 1299"},
    {"name": "Slim fit casual", "model": "INR 1099"},
    {"name": "Classic polo", "model": "INR 1499"},
    {"name": "V-neck tee", "model": "INR 540"},
    {"name": "Graphic tee", "model": "INR 2100"},
    {"name": "Hooded sweatshirt", "model": "INR 1690"},
    {"name": "Crew neck sweater", "model": "INR 1390"},
    {"name": "Denim jacket", "model": "INR 1320"},
    {"name": "Leather jacket", "model": "INR 999"},
    {"name": "Bomber jacket", "model": "INR 689"},
    {"name": "Chinos", "model": "INR 920"},
    {"name": "Slim fit jeans", "model": "INR 650"},
    {"name": "Regular fit jeans", "model": "INR 1600"},
    {"name": "Cargo pants", "model": "INR 1279"},
    {"name": "Shorts", "model": "LSR35"},
    {"name": "Track pants", "model": "INR 1199"},
    {"name": "Formal shirt", "model": "INR 1269"},
    {"name": "Casual shirt", "model": "INR 1349"},
    {"name": "Polo shirt", "model": "INR 1290"},
    {"name": "Henley shirt", "model": "INR 1999"},
    {"name": "Blazer", "model": "INR 1001"},
    {"name": "Sweatpants", "model": "INR 454"},
    {"name": "Pullover", "model": "INR 1299"},
    {"name": "Turtleneck sweater", "model": "INR 1300"},
    {"name": "Cardigan", "model": "INR 1349"},
    {"name": "Trench coat", "model": "INR 1265"},
    {"name": "Puffer jacket", "model": "INR 8999"},
  ];
}
